# Generated by Django 4.1.7 on 2023-03-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_itemimages_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
