# Generated by Django 4.1.7 on 2023-03-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Укажите цену товара', verbose_name='Колличество единиц товара')),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemImage',
            new_name='ProductImage',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='items.order'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_order', to='items.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='items.ProductOrder', to='items.product'),
        ),
    ]
